:art:

diff --git a/bash/bash_aliases b/bash/bash_aliases
--- a/bash/bash_aliases
+++ b/bash/bash_aliases
@@ -7,16 +7,16 @@ alias egrep='egrep --color=auto'
 # GNU ls color
 alias ls='ls --color'
 alias ll='ls -l'
-alias la='ls -Al'               # Show hidden files
-alias lx='ls -lXB'              # Sort by extension
-alias lk='ls -lSr'              # Sort by size
-alias lc='ls -lcr'				# Sort by modification time
-alias lu='ls -lur'				# Sort by access time
-alias lr='ls -lR'               # Recursion ls
-alias lt='ls -ltr'              # Sort by date
+alias la='ls -Al'       # Show hidden files
+alias lx='ls -lXB'      # Sort by extension
+alias lk='ls -lSr'      # Sort by size
+alias lc='ls -lcr'      # Sort by modification time
+alias lu='ls -lur'      # Sort by access time
+alias lr='ls -lR'       # Recursion ls
+alias lt='ls -ltr'      # Sort by date
 alias lm='ls -al |more'
 alias lsd='ls -d */'
-alias tree='tree -C'			# tree display color
+alias tree='tree -C'    # tree display color
 
 # safety features
 alias cp='cp -i'
@@ -89,64 +89,53 @@ alias df='df -kTh'
 #----------------------------------------------------------
 # Make the following commands run in background automatically:
 #----------------------------------------------------------
-function mkcd()
-{
-	mkdir $1
-	cd $1
-}
+function mkcd() { mkdir -p $@ && cd "$_"; }
 
 function exz()
 {
-    if [ -f $1 ] ; then
-        case $1 in
-            *.tar.bz2)   tar xjf $1     ;;
-            *.tar.gz)    tar xzf $1     ;;
-            *.bz2)       bunzip2 $1     ;;
-            *.rar)       rar x $1       ;;
-            *.gz)        gunzip $1      ;;
-            *.tar)       tar xf $1      ;;
-            *.tbz2)      tar xjf $1     ;;
-            *.tgz)       tar xzf $1     ;;
-            *.zip)       unzip $1       ;;
-            *.Z)         uncompress $1  ;;
-            *.7z)        7z x $1        ;;
-            *)           echo "'$1' cannot be extracted via extract()" ;;
-        esac
-    else
-        echo "'$1' is not a valid file"
-    fi
+  if [ -f $1 ] ; then
+    case $1 in
+      *.tar.bz2)   tar xjf $1     ;;
+      *.tar.gz)    tar xzf $1     ;;
+      *.bz2)       bunzip2 $1     ;;
+      *.rar)       rar x $1       ;;
+      *.gz)        gunzip $1      ;;
+      *.tar)       tar xf $1      ;;
+      *.tbz2)      tar xjf $1     ;;
+      *.tgz)       tar xzf $1     ;;
+      *.zip)       unzip $1       ;;
+      *.Z)         uncompress $1  ;;
+      *.7z)        7z x $1        ;;
+      *)           echo "'$1' cannot be extracted via extract()" ;;
+    esac
+  else
+    echo "'$1' is not a valid file"
+  fi
 }
 
 function pcz()
 {
-    if [ $1 ] ; then
-        case $1 in
-            tbz)    tar cjvf $2.tar.bz2 $2      ;;
-            tgz)    tar czvf $2.tar.gz  $2      ;;
-            tar)    tar cpvf $2.tar  $2         ;;
-            bz2)    bzip $2                     ;;
-            gz)     gzip -c -9 -n $2 > $2.gz    ;;
-            zip)    zip -r $2.zip $2            ;;
-            7z)     7z a $2.7z $2               ;;
-            *)     echo "'$1' Cannot be packed via pack()" ;;
-        esac
-    else
-            echo "'$1' is not a valid file"
-    fi
+  if [ $1 ] ; then
+    case $1 in
+      tbz) tar cjvf $2.tar.bz2 $2      ;;
+      tgz) tar czvf $2.tar.gz  $2      ;;
+      tar) tar cpvf $2.tar  $2         ;;
+      bz2) bzip $2                     ;;
+      gz)  gzip -c -9 -n $2 > $2.gz    ;;
+      zip) zip -r $2.zip $2            ;;
+      7z)  7z a $2.7z $2               ;;
+      *)     echo "'$1' Cannot be packed via pack()" ;;
+    esac
+  else
+    echo "'$1' is not a valid file"
+  fi
 }
 
-function calc()
-{
-    echo "$*" | bc;
-}
+function calc() { echo "$*" | bc; }
 
-function te()  # Wrapper around xemacs/gnuserv ...
+function te()
 {
-	if [ "$(gnuclient -batch -eval t 2>&-)" == "t" ]; then
-		gnuclient -q "$@";
-	else
-		( xemacs "$@" &);
-	fi
+  [ "$(gnuclient -batch -eval t 2>&-)" == "t" ] && gnuclient -q "$@" || ( xemacs "$@" &)
 }
 
 function soffice()    { command soffice         "$@" & }
@@ -160,4 +149,4 @@ function eog()        { command eog             "$@" & }
 
 [ -f $HOME/.bash_aliases_local ] && . $HOME/.bash_aliases_local
 
-# vim: set syn=sh sw=4 ts=4 sts=4 et tw=78 foldmarker={,} foldlevel=0 foldmethod=marker:
+# vim: set ft=sh syn=sh sw=2 ts=2 sts=2 et tw=78 foldmarker={,} foldlevel=0 foldmethod=marker:
